from app.models import Activity, DerivedMetric, CheckIn
from app.services.coaching.advisor import generate_advice_structure

def test_advice_pain_severe():
    act = Activity(moving_time_s=1800)
    # Simulate Flag generated by analysis
    metrics = DerivedMetric(flags=["pain_severe"], activity_class="Easy Run")
    checkin = CheckIn(pain_score=8)
    
    advice = generate_advice_structure(act, metrics, None, [], checkin)
    
    assert advice["verdict"] == "Stop and Assess."
    assert advice["next_run"]["type"] == "Rest"
    assert "High pain detected" in advice["warnings"][0]

def test_advice_intensity_discipline():
    act = Activity(moving_time_s=3600) # 60 min
    metrics = DerivedMetric(flags=["intensity_too_high_for_easy"], activity_class="Easy Run")
    
    advice = generate_advice_structure(act, metrics, None, [], None)
    
    assert advice["verdict"] == "Too Fast for Easy."
    assert "above Z2" in advice["evidence"][0]
    assert advice["next_run"]["type"] == "Easy"
    assert "Conversational" in advice["next_run"]["intensity"]

def test_advice_default_strides():
    # Short easy run should suggest strides next
    act = Activity(moving_time_s=1800) # 30 min
    metrics = DerivedMetric(flags=[], activity_class="Easy Run")
    
    advice = generate_advice_structure(act, metrics, None, [], None)
    
    assert advice["verdict"] == "Good Base Building."
    assert "Strides" in advice["next_run"]["type"]
