"""add_efficiency_analysis

Revision ID: 440e584910ff
Revises: f8512d301281
Create Date: 2026-02-09 17:47:29.447252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440e584910ff'
down_revision: Union[str, None] = 'f8512d301281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('derived_metrics', sa.Column('efficiency_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('derived_metrics', 'efficiency_analysis')
    # ### end Alembic commands ###
