"""add interval_structure to derived_metrics

Revision ID: 5704ab8678d6
Revises: c6a94b54b7f5
Create Date: 2026-02-17 15:13:56.174418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5704ab8678d6'
down_revision: Union[str, None] = 'c6a94b54b7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('derived_metrics', sa.Column('interval_structure', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('derived_metrics', 'interval_structure')
    # ### end Alembic commands ###
