"""add risk columns to derived_metrics

Revision ID: 72c36fcd8e76
Revises: 5704ab8678d6
Create Date: 2026-02-17 15:24:02.130849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c36fcd8e76'
down_revision: Union[str, None] = '5704ab8678d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('derived_metrics', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('derived_metrics', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('derived_metrics', sa.Column('risk_reasons', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('derived_metrics', 'risk_reasons')
    op.drop_column('derived_metrics', 'risk_score')
    op.drop_column('derived_metrics', 'risk_level')
    # ### end Alembic commands ###
