"""add_workout_match_interval_kpis_max_hr_source

Revision ID: 9992dd1d047a
Revises: 72c36fcd8e76
Create Date: 2026-02-17 16:24:39.858714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9992dd1d047a'
down_revision: Union[str, None] = '72c36fcd8e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runner_baselines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('typical_easy_pace_s_per_km', sa.Float(), nullable=True),
    sa.Column('typical_easy_hr', sa.Float(), nullable=True),
    sa.Column('typical_long_run_duration_s', sa.Integer(), nullable=True),
    sa.Column('typical_weekly_distance_m', sa.Float(), nullable=True),
    sa.Column('typical_weekly_run_count', sa.Integer(), nullable=True),
    sa.Column('typical_efficiency', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('derived_metrics', sa.Column('workout_match', sa.JSON(), nullable=True))
    op.add_column('derived_metrics', sa.Column('interval_kpis', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('max_hr_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'max_hr_source')
    op.drop_column('derived_metrics', 'interval_kpis')
    op.drop_column('derived_metrics', 'workout_match')
    op.drop_table('runner_baselines')
    # ### end Alembic commands ###
