"""add_ai_commentary

Revision ID: c7b52a98789e
Revises: 3bf573caa922
Create Date: 2026-02-05 09:39:23.571886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b52a98789e'
down_revision: Union[str, None] = '3bf573caa922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advice', sa.Column('ai_commentary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advice', 'ai_commentary')
    # ### end Alembic commands ###
