"""add_advice_structured_report

Revision ID: cb2320704c0d
Revises: da8c5e359ac9
Create Date: 2026-02-05 12:05:08.861333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2320704c0d'
down_revision: Union[str, None] = 'da8c5e359ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advice', sa.Column('structured_report', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advice', 'structured_report')
    # ### end Alembic commands ###
