"""add_profile_max_hr

Revision ID: da8c5e359ac9
Revises: ce70a6dd60d3
Create Date: 2026-02-05 11:57:51.695675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da8c5e359ac9'
down_revision: Union[str, None] = 'ce70a6dd60d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('max_hr', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'max_hr')
    # ### end Alembic commands ###
