"""add_stops_analysis

Revision ID: f8512d301281
Revises: cb2320704c0d
Create Date: 2026-02-09 17:19:23.236575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8512d301281'
down_revision: Union[str, None] = 'cb2320704c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advice')
    op.add_column('derived_metrics', sa.Column('stops_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('derived_metrics', 'stops_analysis')
    op.create_table('advice',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('verdict', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('next_run', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('week_adjustment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('warnings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('full_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('ai_commentary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('structured_report', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('advice_activity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('advice_pkey')),
    sa.UniqueConstraint('activity_id', name=op.f('advice_activity_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
